### ISSUE TITLE
Does not work with ApplicationInsights 2.14.0

### ISSUE THREAD

**Issue by lukaszkierepka** [Socolin/ApplicationInsightsRiderPlugin#1]
Works fine with 2.13.1 but does not show anything after updating to 2.14.0

**Comment by Socolin** [comment]
Thanks, I've fixed this in 138518cda0a3a542f67be015e4fb016e6ae805ab.

Microsoft changed the values sent in the field `name` to identify the type of telemetry.

I published a new version for rider 2020.1.
It should be available tomorrow when it have been reviewed.

**Comment by Socolin** [comment]
New version should be available, can you confirm it fixed your issue ?

**Comment by lukaszkierepka** [comment]
Issue is fixed in the new version. Thank you
