### ISSUE TITLE
Wrong font (lines squeezed vertically)?

### ISSUE THREAD

**Issue by deyanp** [Socolin/ApplicationInsightsRiderPlugin#10]
Any idea why the rows are squeezed on my install:

![image](https://user-images.githubusercontent.com/25847560/142402626-ab803224-ce4d-4d0c-a63a-bf09ca14e89c.png)

Running Rider 2021.2.2 (Oct 8, 2021) on Ubuntu 21.10 ...

**Comment by Socolin** [comment]
Hello,

Can you check if it's the same with 2021.3 EAP.
Also what font / font size is configured in your IDE ?

**Comment by deyanp** [comment]
@Socolin , these are all font-related settings I could find:

![image](https://user-images.githubusercontent.com/25847560/142450166-b50eace2-6d5a-4a54-9f6d-8036064a8698.png)

![image](https://user-images.githubusercontent.com/25847560/142450121-dc4b54f4-c6c0-4671-a28b-98cc1ec6a920.png)

![image](https://user-images.githubusercontent.com/25847560/142450214-c5a8d6ab-5237-4b6a-8ea5-8493a764d673.png)

![image](https://user-images.githubusercontent.com/25847560/142450240-a5101b0a-4a79-4e9b-ad66-2892553c9e76.png)

![image](https://user-images.githubusercontent.com/25847560/142450267-6c4559b2-b7ab-44b5-b8a1-d80fa5661408.png)

![image](https://user-images.githubusercontent.com/25847560/142450297-8e456a18-d10c-4253-9465-98a5da5791e4.png)

Is 2021.3 EAP stable enough to work on? I am using this for my day work ...

**Comment by Socolin** [comment]
I'll take a look when I have some time.

With the toolbox https://www.jetbrains.com/toolbox-app/ you can very easily have both version on your computer (2021.2 and EAP) so you can just try if it's better on the new version and switch back quickly to stable if you have any problem. EAP is in "bug fixing" phase right now and I'm using it without problem (but it may depends on your usage)

![image](https://user-images.githubusercontent.com/539620/142456117-29d92275-2fbb-49c6-abf5-e2e054a77678.png)

**Comment by igelineau** [comment]
I'm still getting this issue with 2023.1.3. 
It occurs with and without a custom font.
Reducing the font size does help but I would need to set it extremely low for it to be readable.
I have a HiDPI 4K monitor, it might be a possible cause.

**Comment by igelineau** [comment]
this is what it looks like with font Inter and font size 20:
![image](https://github.com/Socolin/ApplicationInsightsRiderPlugin/assets/11037499/3bb7b7c0-8273-471a-bbe2-5aa8932e5855)

**Comment by Socolin** [comment]
Ok, it should be related to the DPI then, I don't have a way to test this, I'll try to take a look if I find something obvious

**Comment by igelineau** [comment]
I looked a bit and it seems that I'm running into this bug:
https://bugs.openjdk.org/browse/JDK-8029087

If adding a setting to set a custom row height is not too complicated, I would be ok with that, but I understand it doesn't seem to affect many people :S

**Comment by Socolin** [comment]
There is tooling in inteliji code for this kind of things I'll need to dig into it

**Comment by Socolin** [comment]
Can you test this build https://github.com/Socolin/ApplicationInsightsRiderPlugin/actions/runs/5495937598 ? Download the zip and install the plugin from disk

**Comment by igelineau** [comment]
With this build everything looks fine, this fixes it.
Thank you for looking at it so quickly!
