### ISSUE TITLE
Update to 2022.1

### ISSUE THREAD

**Issue by bw-flagship** [Socolin/ApplicationInsightsRiderPlugin#12]
Thanks for this amazing plugin!
Would be great if you could support 2022.1.

I tried to submit a PR myself but since I have absolutely NO idea of java and especially gradle, I cannot get it to run locally.

Thanks!

**Comment by Socolin** [comment]
I started working on the update but I encountered a bug and I don't know how to fix it. I asked on slack but I did not get any help so far I'll try to find some help elsewhere
