### ISSUE TITLE
Appearing  under other debug tabs

### ISSUE THREAD

**Issue by benjaminvaneck** [Socolin/ApplicationInsightsRiderPlugin#18]
I love the plugin. Since a couple of weeks it started appearing in de debug windows, but under all other tabs which make is not nice to debug. Is there any way to reset the position of the application insights tab?

![image](https://github.com/Socolin/ApplicationInsightsRiderPlugin/assets/93879563/00b555e5-e957-4167-acaa-ec7c42eaf083)

**Comment by Socolin** [comment]
There is a button to reset the layout on the right of the tool window, I don't know why this happen sometimes :p (I don't have much control on this part in the plugin)

![image](https://github.com/Socolin/ApplicationInsightsRiderPlugin/assets/539620/6031c45a-21b8-4087-a71b-bd70959d8f41)

**Comment by benjaminvaneck** [comment]
Ok, yes this solved the issue. Thx!
