### ISSUE TITLE
Open telemetry support

### ISSUE THREAD

**Issue by ozkanpakdil** [Socolin/ApplicationInsightsRiderPlugin#22]
I have been trying to have open telemetry debug viewer, I thought it would be as simple as adding below lines to [here](https://github.com/Socolin/ApplicationInsightsRiderPlugin/blob/7b72a85f315b67d1c32c8a7a68ae39da8ee43c53/src/main/resources/META-INF/plugin.xml#L36)

```
<dependencySupport kind="dotnet" coordinate="OpenTelemetry" displayName="Application Insights Debug Log Viewer"/>
<dependencySupport kind="dotnet" coordinate="OpenTelemetry.Trace" displayName="Application Insights Debug Log Viewer"/>
<dependencySupport kind="dotnet" coordinate="OpenTelemetry.Metrics" displayName="Application Insights Debug Log Viewer"/>
<dependencySupport kind="dotnet" coordinate="OpenTelemetry.Logs" displayName="Application Insights Debug Log Viewer"/>
<dependencySupport kind="dotnet" coordinate="OpenTelemetry.Exporter.OpenTelemetryProtocol" displayName="Application Insights Debug Log Viewer"/>
```
but that was not enough, looks like [here](https://github.com/Socolin/ApplicationInsightsRiderPlugin/blob/7b72a85f315b67d1c32c8a7a68ae39da8ee43c53/src/main/java/fr/socolin/applicationinsights/ApplicationInsightsSession.java#L79)
```java
        dotNetDebugProcess.getSessionProxy().getTargetDebug().advise(lifetime, outputMessageWithSubject -> {
            Telemetry telemetry = telemetryFactory.tryCreateFromDebugOutputLog(outputMessageWithSubject.getOutput());
            if (telemetry != null) {
                addTelemetry(telemetry);
            }
            return Unit.INSTANCE;
        });
```
is called once and never call again, I mean the line `Telemetry telemetry = telemetryFactory.tryCreateFromDebugOutputLog(outputMessageWithSubject.getOutput());` never get called for opentelemetry, I suspect opentelemetry data sender is not using something related dotNetDebugProcess.getSessionProxy().getTargetDebug() but could not figure that out, any pointers please ? 

if I can manage to get the debug log I can write the further json parser steps

**Comment by Socolin** [comment]
Quickly If I remember correctly (it's been a long time since I wrote this) it's only looking for json in the Debug output. The plugin subscribe to an event and each time a new line is added the event is executed then it try to parse the AI json.

The lines here https://github.com/Socolin/ApplicationInsightsRiderPlugin/blob/7b72a85f315b67d1c32c8a7a68ae39da8ee43c53/src/main/resources/META-INF/plugin.xml#L36 are only to suggest the plugin if you have this nuget installed.

The following lines are supposed to be executed for each line from the Debug output

![image](https://github.com/user-attachments/assets/da200a25-f9b5-4d3c-ae4d-3c8c8794897c)


```
  Telemetry telemetry = telemetryFactory.tryCreateFromDebugOutputLog(outputMessageWithSubject.getOutput());
            if (telemetry != null) {
                addTelemetry(telemetry);
            }
```

**Comment by Socolin** [comment]
Here what the line it's trying to read looks like
![image](https://github.com/user-attachments/assets/010fa965-a5a3-4e80-9957-b194d7e635f7)

**Comment by ozkanpakdil** [comment]
thank you very much @Socolin , is it okay if I make a separate plugin for open telemetry or do you like to have a PR here ?

**Comment by Socolin** [comment]
It might be confusing to have 2 plugins doing almost the same things, but the branding would not be the same exactly.
- If you do a PR I'll merge it (Put the OT logs in a OT tabs).
- If you want to do another plugin, I would only suggest to drop the AI part to avoid having both plugin overlapping.

I have some improvement I would like to do on this plugin, larger than AI, so I was already thinking about renaming the plugin or creating a new one, but I'm not sure if and when I will have the energy to look into this again.
I asked JetBrains team if there is a way to rename a plugin or redirect users from 1 plugin to another, I'll let you know when I have more info.

At the end, technically speaking, this is MIT license, so if you want to fork and create your plugin do as you want :) 
If you don't already maintain a plugin, I just want to let you know that every 4 month, an update is needed and the JetBrains API might have changed.
This plugin is currently low maintenance (not many API are used) but keep in mind this if you create your own, it's kind of a commitment to keep it updated.

**Comment by ozkanpakdil** [comment]
https://plugins.jetbrains.com/plugin/25499-opentelemetry-debug-log-viewer

in case anyone find this page, I published the plugin there 🥳big thanks to @Socolin I just trim the appinsights side and change the json parser a little bit, it does not have those fancy counters, if anyone needs it I am open to PRs 😊

**Comment by Socolin** [comment]
Hello,

I've published a new plugin replacing this one. adding support for Open Telemetry without the need of an extra nuget package.

More info: https://github.com/Socolin/ApplicationInsightsRiderPlugin/issues/27
